### ISSUE TITLE
Could you publish this theme on marmalade?

### ISSUE THREAD

**Issue by bastibe** [maio/eink-emacs#2]
Hi,

I very much like your theme! Great work there!
Could you upload it to marmalade or melpa-stable, so I can install it through the Emacs package manager?

Thank you!

**Comment by maio** [comment]
Hi,

thanks for your kind words. Few hour ago I tagged master with `v1.0.0` and now it seems to be available in MELPA stable.

Unfortunately I don't have experience with marmelade so that will take little bit longer.

**Comment by bastibe** [comment]
Thank you very much! Don't worry about Marmalade, I am happy with MELPA stable!
