### ISSUE TITLE
highlight (when mouseover) does not works with enhanced-ruby-mode

### ISSUE THREAD

**Issue by edipofederle** [maio/eink-emacs#5]
Hi,

First of all, congratulations for your work. Really good.

I just added your theme in my emacs configurations but the highlight (when mouseover in _class_, for example) nothing happens.

![screen shot 2016-07-04 at 7 07 45 pm](https://cloud.githubusercontent.com/assets/50778/16570375/00031616-421a-11e6-9155-6b317711c36b.png)

If I use ruby-mode, it works as expected

![screen shot 2016-07-04 at 7 08 46 pm](https://cloud.githubusercontent.com/assets/50778/16570378/10cda77c-421a-11e6-8e53-30921242eaa8.png)

If you have any idea where I appreciate it

Thanks in advance.

**Comment by greduan** [comment]
May this be a `ruby-mode` specific thing? Or provided by each mode for it's particular file and stuff?

**Comment by maio** [comment]
Sorry, I'm not really sure that I understand what you mean. :/ Would you mind explaining it little bit more?

I tried default emacs theme with ruby mode and nothing gets highlighted on mouseover either. What do you mean by highlight?

**Comment by edipofederle** [comment]
Hi everyone,

Sorry for the poorly worded question..

highlight: I mean bold ...

**Comment by edipofederle** [comment]
I am sorry for the confusion. :(

What happen is that I was using another theme color (which is based on your).
So I mixed up both.
Please, disregard this issue.

And thanks for reply.

**Comment by maio** [comment]
No problem. :)
